all:
	g++ -g -Wall -std=c++11 -o test_find std_find.cpp  
	g++ -g -Wall -std=c++11 -o test_search std_search.cpp  
	g++ -g -Wall -std=c++11 -o test_upper_bound upper_bound.cpp  
	g++ -g -Wall -std=c++11 -o test_heap std_heap.cpp  
clean:
	rm -f test_find
	rm -f test_search
	rm -f test_upper_bound
	rm -f test_heap
