all:
	g++ -g -std=c++11 -o test_objpool test_objpool.cpp
	g++ -g -std=c++11 -o test_rawalloc test_rawalloc.cpp
	g++ -g -std=c++11 -o test_tmalloc test_tmalloc.cpp
clean:
	rm -f test_objpool
	rm -f test_rawalloc
	rm -f test_tmalloc
