all:
	g++ --std=c++11 -pthread -o test_by_func pthread_by_func.cpp
	g++ --std=c++11 -pthread -o test_by_functor pthread_by_functor.cpp
	g++ --std=c++11 -pthread -o test_by_lambda pthread_by_lambda.cpp
clean:
	rm -f test_by_func test_by_functor test_by_lambda
