all:
	g++ -g -Wall -std=c++11 -o test_move std_move.cpp  
	g++ -g -Wall -std=c++11 -o test_bind std_bind.cpp  
	g++ -g -Wall -std=c++11 -o test_function std_function.cpp  
	g++ -g -Wall -std=c++11 -o test_emplace_back std_emplace_back.cpp  
	g++ -g -Wall -std=c++11 -pthread -o test_lock_guard std_lock_guard.cpp  
	g++ -g -Wall -std=c++11 -o test_shared_from_this std_shared_from_this.cpp  
clean:
	rm -f test_move test_bind test_function test_emplace_back test_lock_guard test_shared_from_this
