all:
	g++ -g -o test_unique unique_ptr.cpp --std=c++11
	g++ -g -o test_shared shared_ptr.cpp --std=c++11
	g++ -g -o test_weak   weak_ptr.cpp --std=c++11
clean:
	rm -f test_unique test_shared test_weak
