all:
	g++ -g -Wall -std=c++11 -o test_move std_move.cpp  
	g++ -g -Wall -std=c++11 -o test_bind std_bind.cpp  
	g++ -g -Wall -std=c++11 -o test_function std_function.cpp  
clean:
	rm -f test_move test_bind test_function
